modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
    modId="fp2"
    version="${file.jarVersion}"
    displayName="FarPlaneTwo"
    description='''The successor to Foghrye4's CWGFarPlaneView'''

[[dependencies.fp2]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fp2]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fp2]]
    modId="terrain_diffusion_mc"
    type="required"
    versionRange="[2.1.0,)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="fp2.mixins.json"
